#!/bin/csh
java -Xmx70000m  -Ddatabase_type=ORACLE -Drole_string=FILTER_CREATOR -d64 -Djava.util.prefs.systemRoot=/tmp/.java -Djava.util.prefs.syncInterval=2000000  -cp "/opt/gnem/java/applications/DetectionFramework/latest/*" llnl.gnem.apps.detection.sdBuilder.Builder $*


