#!/bin/csh
java -ms1024m -Xmx140000m -d64 -Djava.util.prefs.systemRoot=/tmp/.java -Djava.util.prefs.syncInterval=2000000  -cp "/opt/gnem/java/applications/DetectionFramework/latest/*" llnl.gnem.apps.detection.FrameworkRunner $*


